package ru.burmistrov.tm.api.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-18T12:22:54.110+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://service.api.tm.burmistrov.ru/", name = "IProjectService")
@XmlSeeAlso({ObjectFactory.class})
public interface IProjectService {

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/IProjectService/findAllProjectsSortByDateEndRequest", output = "http://service.api.tm.burmistrov.ru/IProjectService/findAllProjectsSortByDateEndResponse")
    @RequestWrapper(localName = "findAllProjectsSortByDateEnd", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindAllProjectsSortByDateEnd")
    @ResponseWrapper(localName = "findAllProjectsSortByDateEndResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindAllProjectsSortByDateEndResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.burmistrov.tm.api.service.Project> findAllProjectsSortByDateEnd(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/IProjectService/findProjectByDescriptionRequest", output = "http://service.api.tm.burmistrov.ru/IProjectService/findProjectByDescriptionResponse")
    @RequestWrapper(localName = "findProjectByDescription", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindProjectByDescription")
    @ResponseWrapper(localName = "findProjectByDescriptionResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindProjectByDescriptionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.burmistrov.tm.api.service.Project findProjectByDescription(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/IProjectService/removeProjectByIdRequest", output = "http://service.api.tm.burmistrov.ru/IProjectService/removeProjectByIdResponse")
    @RequestWrapper(localName = "removeProjectById", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.RemoveProjectById")
    @ResponseWrapper(localName = "removeProjectByIdResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.RemoveProjectByIdResponse")
    public void removeProjectById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/IProjectService/createProjectRequest", output = "http://service.api.tm.burmistrov.ru/IProjectService/createProjectResponse", fault = {@FaultAction(className = ParseException_Exception.class, value = "http://service.api.tm.burmistrov.ru/IProjectService/createProject/Fault/ParseException")})
    @RequestWrapper(localName = "createProject", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.CreateProject")
    @ResponseWrapper(localName = "createProjectResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.CreateProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.burmistrov.tm.api.service.Project createProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws ParseException_Exception;

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/IProjectService/removeAllProjectsRequest", output = "http://service.api.tm.burmistrov.ru/IProjectService/removeAllProjectsResponse")
    @RequestWrapper(localName = "removeAllProjects", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.RemoveAllProjects")
    @ResponseWrapper(localName = "removeAllProjectsResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.RemoveAllProjectsResponse")
    public void removeAllProjects(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/IProjectService/findAllProjectsSortByStatusRequest", output = "http://service.api.tm.burmistrov.ru/IProjectService/findAllProjectsSortByStatusResponse")
    @RequestWrapper(localName = "findAllProjectsSortByStatus", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindAllProjectsSortByStatus")
    @ResponseWrapper(localName = "findAllProjectsSortByStatusResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindAllProjectsSortByStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.burmistrov.tm.api.service.Project> findAllProjectsSortByStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/IProjectService/findAllProjectsRequest", output = "http://service.api.tm.burmistrov.ru/IProjectService/findAllProjectsResponse")
    @RequestWrapper(localName = "findAllProjects", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindAllProjects")
    @ResponseWrapper(localName = "findAllProjectsResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindAllProjectsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.burmistrov.tm.api.service.Project> findAllProjects(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/IProjectService/updateProjectByIdRequest", output = "http://service.api.tm.burmistrov.ru/IProjectService/updateProjectByIdResponse", fault = {@FaultAction(className = ParseException_Exception.class, value = "http://service.api.tm.burmistrov.ru/IProjectService/updateProjectById/Fault/ParseException")})
    @RequestWrapper(localName = "updateProjectById", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.UpdateProjectById")
    @ResponseWrapper(localName = "updateProjectByIdResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.UpdateProjectByIdResponse")
    public void updateProjectById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    ) throws ParseException_Exception;

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/IProjectService/findProjectByNameRequest", output = "http://service.api.tm.burmistrov.ru/IProjectService/findProjectByNameResponse")
    @RequestWrapper(localName = "findProjectByName", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindProjectByName")
    @ResponseWrapper(localName = "findProjectByNameResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindProjectByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.burmistrov.tm.api.service.Project findProjectByName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/IProjectService/findAllProjectsSortByDateBeginRequest", output = "http://service.api.tm.burmistrov.ru/IProjectService/findAllProjectsSortByDateBeginResponse")
    @RequestWrapper(localName = "findAllProjectsSortByDateBegin", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindAllProjectsSortByDateBegin")
    @ResponseWrapper(localName = "findAllProjectsSortByDateBeginResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindAllProjectsSortByDateBeginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.burmistrov.tm.api.service.Project> findAllProjectsSortByDateBegin(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
