package ru.burmistrov.tm.api.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-18T12:22:54.379+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://service.api.tm.burmistrov.ru/", name = "ITaskService")
@XmlSeeAlso({ObjectFactory.class})
public interface ITaskService {

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/ITaskService/findTaskByDescriptionRequest", output = "http://service.api.tm.burmistrov.ru/ITaskService/findTaskByDescriptionResponse")
    @RequestWrapper(localName = "findTaskByDescription", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindTaskByDescription")
    @ResponseWrapper(localName = "findTaskByDescriptionResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindTaskByDescriptionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.burmistrov.tm.api.service.Task findTaskByDescription(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/ITaskService/findAllTasksSortByDateEndRequest", output = "http://service.api.tm.burmistrov.ru/ITaskService/findAllTasksSortByDateEndResponse")
    @RequestWrapper(localName = "findAllTasksSortByDateEnd", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindAllTasksSortByDateEnd")
    @ResponseWrapper(localName = "findAllTasksSortByDateEndResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindAllTasksSortByDateEndResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.burmistrov.tm.api.service.Task> findAllTasksSortByDateEnd(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/ITaskService/removeTaskByIdRequest", output = "http://service.api.tm.burmistrov.ru/ITaskService/removeTaskByIdResponse")
    @RequestWrapper(localName = "removeTaskById", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.RemoveTaskById")
    @ResponseWrapper(localName = "removeTaskByIdResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.RemoveTaskByIdResponse")
    public void removeTaskById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/ITaskService/updateTaskByIdRequest", output = "http://service.api.tm.burmistrov.ru/ITaskService/updateTaskByIdResponse", fault = {@FaultAction(className = ParseException_Exception.class, value = "http://service.api.tm.burmistrov.ru/ITaskService/updateTaskById/Fault/ParseException")})
    @RequestWrapper(localName = "updateTaskById", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.UpdateTaskById")
    @ResponseWrapper(localName = "updateTaskByIdResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.UpdateTaskByIdResponse")
    public void updateTaskById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5
    ) throws ParseException_Exception;

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/ITaskService/findAllTasksRequest", output = "http://service.api.tm.burmistrov.ru/ITaskService/findAllTasksResponse")
    @RequestWrapper(localName = "findAllTasks", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindAllTasks")
    @ResponseWrapper(localName = "findAllTasksResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindAllTasksResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.burmistrov.tm.api.service.Task> findAllTasks(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/ITaskService/findTaskByNameRequest", output = "http://service.api.tm.burmistrov.ru/ITaskService/findTaskByNameResponse")
    @RequestWrapper(localName = "findTaskByName", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindTaskByName")
    @ResponseWrapper(localName = "findTaskByNameResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindTaskByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.burmistrov.tm.api.service.Task findTaskByName(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/ITaskService/createTaskRequest", output = "http://service.api.tm.burmistrov.ru/ITaskService/createTaskResponse", fault = {@FaultAction(className = ParseException_Exception.class, value = "http://service.api.tm.burmistrov.ru/ITaskService/createTask/Fault/ParseException")})
    @RequestWrapper(localName = "createTask", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.CreateTask")
    @ResponseWrapper(localName = "createTaskResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.CreateTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.burmistrov.tm.api.service.Task createTask(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    ) throws ParseException_Exception;

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/ITaskService/findAllTasksSortByDateBeginRequest", output = "http://service.api.tm.burmistrov.ru/ITaskService/findAllTasksSortByDateBeginResponse")
    @RequestWrapper(localName = "findAllTasksSortByDateBegin", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindAllTasksSortByDateBegin")
    @ResponseWrapper(localName = "findAllTasksSortByDateBeginResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindAllTasksSortByDateBeginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.burmistrov.tm.api.service.Task> findAllTasksSortByDateBegin(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/ITaskService/removeAllTasksInProjectRequest", output = "http://service.api.tm.burmistrov.ru/ITaskService/removeAllTasksInProjectResponse")
    @RequestWrapper(localName = "removeAllTasksInProject", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.RemoveAllTasksInProject")
    @ResponseWrapper(localName = "removeAllTasksInProjectResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.RemoveAllTasksInProjectResponse")
    public void removeAllTasksInProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/ITaskService/findAllTasksSortByStatusRequest", output = "http://service.api.tm.burmistrov.ru/ITaskService/findAllTasksSortByStatusResponse")
    @RequestWrapper(localName = "findAllTasksSortByStatus", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindAllTasksSortByStatus")
    @ResponseWrapper(localName = "findAllTasksSortByStatusResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindAllTasksSortByStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.burmistrov.tm.api.service.Task> findAllTasksSortByStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/ITaskService/removeAllTasksRequest", output = "http://service.api.tm.burmistrov.ru/ITaskService/removeAllTasksResponse")
    @RequestWrapper(localName = "removeAllTasks", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.RemoveAllTasks")
    @ResponseWrapper(localName = "removeAllTasksResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.RemoveAllTasksResponse")
    public void removeAllTasks(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://service.api.tm.burmistrov.ru/ITaskService/findAllTasksInProjectRequest", output = "http://service.api.tm.burmistrov.ru/ITaskService/findAllTasksInProjectResponse")
    @RequestWrapper(localName = "findAllTasksInProject", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindAllTasksInProject")
    @ResponseWrapper(localName = "findAllTasksInProjectResponse", targetNamespace = "http://service.api.tm.burmistrov.ru/", className = "ru.burmistrov.tm.api.service.FindAllTasksInProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.burmistrov.tm.api.service.Task> findAllTasksInProject(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
