
package ru.burmistrov.tm.api.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-18T12:22:54.379+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "ParseException", targetNamespace = "http://service.api.tm.burmistrov.ru/")
public class ParseException_Exception extends Exception {

    private ru.burmistrov.tm.api.service.ParseException parseException;

    public ParseException_Exception() {
        super();
    }

    public ParseException_Exception(String message) {
        super(message);
    }

    public ParseException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ParseException_Exception(String message, ru.burmistrov.tm.api.service.ParseException parseException) {
        super(message);
        this.parseException = parseException;
    }

    public ParseException_Exception(String message, ru.burmistrov.tm.api.service.ParseException parseException, java.lang.Throwable cause) {
        super(message, cause);
        this.parseException = parseException;
    }

    public ru.burmistrov.tm.api.service.ParseException getFaultInfo() {
        return this.parseException;
    }
}
