package ru.burmistrov.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-21T11:57:20.701+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.burmistrov.ru/", name = "AdminEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface AdminEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByFasterXmlJsonRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByFasterXmlJsonResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByFasterXmlJson/Fault/IOException"), @FaultAction(className = CloneNotSupportedException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByFasterXmlJson/Fault/CloneNotSupportedException")})
    @RequestWrapper(localName = "saveDataByFasterXmlJson", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByFasterXmlJson")
    @ResponseWrapper(localName = "saveDataByFasterXmlJsonResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByFasterXmlJsonResponse")
    public void saveDataByFasterXmlJson(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws IOException_Exception, CloneNotSupportedException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByJaxbJsonRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByJaxbJsonResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByJaxbJson/Fault/IOException"), @FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByJaxbJson/Fault/JAXBException"), @FaultAction(className = CloneNotSupportedException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByJaxbJson/Fault/CloneNotSupportedException")})
    @RequestWrapper(localName = "loadDataByJaxbJson", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByJaxbJson")
    @ResponseWrapper(localName = "loadDataByJaxbJsonResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByJaxbJsonResponse")
    public void loadDataByJaxbJson(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws IOException_Exception, JAXBException_Exception, CloneNotSupportedException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByDefaultRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByDefaultResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByDefault/Fault/IOException"), @FaultAction(className = ClassNotFoundException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByDefault/Fault/ClassNotFoundException"), @FaultAction(className = CloneNotSupportedException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByDefault/Fault/CloneNotSupportedException")})
    @RequestWrapper(localName = "loadDataByDefault", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByDefault")
    @ResponseWrapper(localName = "loadDataByDefaultResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByDefaultResponse")
    public void loadDataByDefault(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws IOException_Exception, ClassNotFoundException_Exception, CloneNotSupportedException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/createUserRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/createUserResponse", fault = {@FaultAction(className = CloneNotSupportedException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/createUser/Fault/CloneNotSupportedException")})
    @RequestWrapper(localName = "createUser", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.CreateUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.burmistrov.tm.endpoint.User createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Role arg7
    ) throws CloneNotSupportedException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByJaxbXmlRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByJaxbXmlResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByJaxbXml/Fault/IOException"), @FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByJaxbXml/Fault/JAXBException"), @FaultAction(className = CloneNotSupportedException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByJaxbXml/Fault/CloneNotSupportedException")})
    @RequestWrapper(localName = "loadDataByJaxbXml", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByJaxbXml")
    @ResponseWrapper(localName = "loadDataByJaxbXmlResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByJaxbXmlResponse")
    public void loadDataByJaxbXml(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws IOException_Exception, JAXBException_Exception, CloneNotSupportedException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByFasterXmlRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByFasterXmlResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByFasterXml/Fault/IOException"), @FaultAction(className = CloneNotSupportedException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByFasterXml/Fault/CloneNotSupportedException")})
    @RequestWrapper(localName = "saveDataByFasterXml", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByFasterXml")
    @ResponseWrapper(localName = "saveDataByFasterXmlResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByFasterXmlResponse")
    public void saveDataByFasterXml(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws IOException_Exception, CloneNotSupportedException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/removeAllUsersRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/removeAllUsersResponse", fault = {@FaultAction(className = CloneNotSupportedException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/removeAllUsers/Fault/CloneNotSupportedException")})
    @RequestWrapper(localName = "removeAllUsers", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.RemoveAllUsers")
    @ResponseWrapper(localName = "removeAllUsersResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.RemoveAllUsersResponse")
    public void removeAllUsers(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws CloneNotSupportedException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByFasterXmlRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByFasterXmlResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByFasterXml/Fault/IOException"), @FaultAction(className = CloneNotSupportedException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByFasterXml/Fault/CloneNotSupportedException")})
    @RequestWrapper(localName = "loadDataByFasterXml", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByFasterXml")
    @ResponseWrapper(localName = "loadDataByFasterXmlResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByFasterXmlResponse")
    public void loadDataByFasterXml(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws IOException_Exception, CloneNotSupportedException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/updateUserByIdRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/updateUserByIdResponse", fault = {@FaultAction(className = CloneNotSupportedException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/updateUserById/Fault/CloneNotSupportedException")})
    @RequestWrapper(localName = "updateUserById", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.UpdateUserById")
    @ResponseWrapper(localName = "updateUserByIdResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.UpdateUserByIdResponse")
    public void updateUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Role arg6
    ) throws CloneNotSupportedException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByJaxbJsonRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByJaxbJsonResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByJaxbJson/Fault/IOException"), @FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByJaxbJson/Fault/JAXBException"), @FaultAction(className = CloneNotSupportedException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByJaxbJson/Fault/CloneNotSupportedException")})
    @RequestWrapper(localName = "saveDataByJaxbJson", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByJaxbJson")
    @ResponseWrapper(localName = "saveDataByJaxbJsonResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByJaxbJsonResponse")
    public void saveDataByJaxbJson(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws IOException_Exception, JAXBException_Exception, CloneNotSupportedException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByDefaultRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByDefaultResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByDefault/Fault/IOException"), @FaultAction(className = CloneNotSupportedException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByDefault/Fault/CloneNotSupportedException")})
    @RequestWrapper(localName = "saveDataByDefault", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByDefault")
    @ResponseWrapper(localName = "saveDataByDefaultResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByDefaultResponse")
    public void saveDataByDefault(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws IOException_Exception, CloneNotSupportedException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/updatePasswordByIdRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/updatePasswordByIdResponse", fault = {@FaultAction(className = CloneNotSupportedException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/updatePasswordById/Fault/CloneNotSupportedException")})
    @RequestWrapper(localName = "updatePasswordById", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.UpdatePasswordById")
    @ResponseWrapper(localName = "updatePasswordByIdResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.UpdatePasswordByIdResponse")
    public void updatePasswordById(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws CloneNotSupportedException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/removeUserByIdRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/removeUserByIdResponse", fault = {@FaultAction(className = CloneNotSupportedException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/removeUserById/Fault/CloneNotSupportedException")})
    @RequestWrapper(localName = "removeUserById", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.RemoveUserById")
    @ResponseWrapper(localName = "removeUserByIdResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.RemoveUserByIdResponse")
    public void removeUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws CloneNotSupportedException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByJaxbXmlRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByJaxbXmlResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByJaxbXml/Fault/IOException"), @FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByJaxbXml/Fault/JAXBException"), @FaultAction(className = CloneNotSupportedException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByJaxbXml/Fault/CloneNotSupportedException")})
    @RequestWrapper(localName = "saveDataByJaxbXml", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByJaxbXml")
    @ResponseWrapper(localName = "saveDataByJaxbXmlResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByJaxbXmlResponse")
    public void saveDataByJaxbXml(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws IOException_Exception, JAXBException_Exception, CloneNotSupportedException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByFasterXmlJsonRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByFasterXmlJsonResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByFasterXmlJson/Fault/IOException"), @FaultAction(className = CloneNotSupportedException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByFasterXmlJson/Fault/CloneNotSupportedException")})
    @RequestWrapper(localName = "loadDataByFasterXmlJson", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByFasterXmlJson")
    @ResponseWrapper(localName = "loadDataByFasterXmlJsonResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByFasterXmlJsonResponse")
    public void loadDataByFasterXmlJson(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws IOException_Exception, CloneNotSupportedException_Exception;
}
