package ru.burmistrov.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-20T11:37:45.763+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.burmistrov.ru/", name = "AdminEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface AdminEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByFasterXmlJsonRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByFasterXmlJsonResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByFasterXmlJson/Fault/IOException")})
    @RequestWrapper(localName = "saveDataByFasterXmlJson", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByFasterXmlJson")
    @ResponseWrapper(localName = "saveDataByFasterXmlJsonResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByFasterXmlJsonResponse")
    public void saveDataByFasterXmlJson(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByDefaultRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByDefaultResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByDefault/Fault/IOException")})
    @RequestWrapper(localName = "saveDataByDefault", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByDefault")
    @ResponseWrapper(localName = "saveDataByDefaultResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByDefaultResponse")
    public void saveDataByDefault(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByJaxbJsonRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByJaxbJsonResponse", fault = {@FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByJaxbJson/Fault/JAXBException")})
    @RequestWrapper(localName = "loadDataByJaxbJson", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByJaxbJson")
    @ResponseWrapper(localName = "loadDataByJaxbJsonResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByJaxbJsonResponse")
    public void loadDataByJaxbJson(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws JAXBException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByDefaultRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByDefaultResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByDefault/Fault/IOException"), @FaultAction(className = ClassNotFoundException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByDefault/Fault/ClassNotFoundException")})
    @RequestWrapper(localName = "loadDataByDefault", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByDefault")
    @ResponseWrapper(localName = "loadDataByDefaultResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByDefaultResponse")
    public void loadDataByDefault(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws IOException_Exception, ClassNotFoundException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByJaxbXmlRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByJaxbXmlResponse", fault = {@FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByJaxbXml/Fault/JAXBException")})
    @RequestWrapper(localName = "loadDataByJaxbXml", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByJaxbXml")
    @ResponseWrapper(localName = "loadDataByJaxbXmlResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByJaxbXmlResponse")
    public void loadDataByJaxbXml(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws JAXBException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByFasterXmlRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByFasterXmlResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByFasterXml/Fault/IOException")})
    @RequestWrapper(localName = "saveDataByFasterXml", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByFasterXml")
    @ResponseWrapper(localName = "saveDataByFasterXmlResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByFasterXmlResponse")
    public void saveDataByFasterXml(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByJaxbXmlRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByJaxbXmlResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByJaxbXml/Fault/IOException"), @FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByJaxbXml/Fault/JAXBException")})
    @RequestWrapper(localName = "saveDataByJaxbXml", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByJaxbXml")
    @ResponseWrapper(localName = "saveDataByJaxbXmlResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByJaxbXmlResponse")
    public void saveDataByJaxbXml(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws IOException_Exception, JAXBException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByFasterXmlRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByFasterXmlResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByFasterXml/Fault/IOException")})
    @RequestWrapper(localName = "loadDataByFasterXml", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByFasterXml")
    @ResponseWrapper(localName = "loadDataByFasterXmlResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByFasterXmlResponse")
    public void loadDataByFasterXml(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByFasterXmlJsonRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByFasterXmlJsonResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/loadDataByFasterXmlJson/Fault/IOException")})
    @RequestWrapper(localName = "loadDataByFasterXmlJson", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByFasterXmlJson")
    @ResponseWrapper(localName = "loadDataByFasterXmlJsonResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LoadDataByFasterXmlJsonResponse")
    public void loadDataByFasterXmlJson(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByJaxbJsonRequest", output = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByJaxbJsonResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByJaxbJson/Fault/IOException"), @FaultAction(className = JAXBException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/AdminEndpoint/saveDataByJaxbJson/Fault/JAXBException")})
    @RequestWrapper(localName = "saveDataByJaxbJson", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByJaxbJson")
    @ResponseWrapper(localName = "saveDataByJaxbJsonResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.SaveDataByJaxbJsonResponse")
    public void saveDataByJaxbJson(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0
    ) throws IOException_Exception, JAXBException_Exception;
}
