package ru.burmistrov.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-21T11:06:58.813+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.burmistrov.ru/", name = "SessionEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface SessionEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/SessionEndpoint/getNewSessionRequest", output = "http://endpoint.tm.burmistrov.ru/SessionEndpoint/getNewSessionResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/SessionEndpoint/getNewSession/Fault/IOException")})
    @RequestWrapper(localName = "getNewSession", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.GetNewSession")
    @ResponseWrapper(localName = "getNewSessionResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.GetNewSessionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.burmistrov.tm.endpoint.Session getNewSession(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws IOException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/SessionEndpoint/logInRequest", output = "http://endpoint.tm.burmistrov.ru/SessionEndpoint/logInResponse")
    @RequestWrapper(localName = "logIn", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LogIn")
    @ResponseWrapper(localName = "logInResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LogInResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.burmistrov.tm.endpoint.User logIn(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
