package ru.burmistrov.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-21T11:57:20.358+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.burmistrov.ru/", name = "UserEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface UserEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/UserEndpoint/updateUserByIdRequest", output = "http://endpoint.tm.burmistrov.ru/UserEndpoint/updateUserByIdResponse", fault = {@FaultAction(className = ValidateAccessException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/UserEndpoint/updateUserById/Fault/ValidateAccessException"), @FaultAction(className = CloneNotSupportedException_Exception.class, value = "http://endpoint.tm.burmistrov.ru/UserEndpoint/updateUserById/Fault/CloneNotSupportedException")})
    @RequestWrapper(localName = "updateUserById", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.UpdateUserById")
    @ResponseWrapper(localName = "updateUserByIdResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.UpdateUserByIdResponse")
    public void updateUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Role arg6
    ) throws ValidateAccessException_Exception, CloneNotSupportedException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/UserEndpoint/logInRequest", output = "http://endpoint.tm.burmistrov.ru/UserEndpoint/logInResponse")
    @RequestWrapper(localName = "logIn", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LogIn")
    @ResponseWrapper(localName = "logInResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LogInResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.burmistrov.tm.endpoint.User logIn(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
