package ru.burmistrov.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-29T18:03:55.479+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.burmistrov.ru/", name = "UserEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface UserEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/UserEndpoint/updateUserByIdRequest", output = "http://endpoint.tm.burmistrov.ru/UserEndpoint/updateUserByIdResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://endpoint.tm.burmistrov.ru/UserEndpoint/updateUserById/Fault/Exception")})
    @RequestWrapper(localName = "updateUserById", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.UpdateUserById")
    @ResponseWrapper(localName = "updateUserByIdResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.UpdateUserByIdResponse")
    public void updateUserById(
        @WebParam(name = "session", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Session session,
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "firstName", targetNamespace = "")
        java.lang.String firstName,
        @WebParam(name = "middleName", targetNamespace = "")
        java.lang.String middleName,
        @WebParam(name = "lastName", targetNamespace = "")
        java.lang.String lastName,
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "role", targetNamespace = "")
        ru.burmistrov.tm.endpoint.Role role
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.burmistrov.ru/UserEndpoint/logInRequest", output = "http://endpoint.tm.burmistrov.ru/UserEndpoint/logInResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://endpoint.tm.burmistrov.ru/UserEndpoint/logIn/Fault/Exception")})
    @RequestWrapper(localName = "logIn", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LogIn")
    @ResponseWrapper(localName = "logInResponse", targetNamespace = "http://endpoint.tm.burmistrov.ru/", className = "ru.burmistrov.tm.endpoint.LogInResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.burmistrov.tm.endpoint.UserDto logIn(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    ) throws Exception_Exception;
}
