
package ru.burmistrov.tm.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-21T11:57:20.358+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "ValidateAccessException", targetNamespace = "http://endpoint.tm.burmistrov.ru/")
public class ValidateAccessException_Exception extends Exception {

    private ru.burmistrov.tm.endpoint.ValidateAccessException validateAccessException;

    public ValidateAccessException_Exception() {
        super();
    }

    public ValidateAccessException_Exception(String message) {
        super(message);
    }

    public ValidateAccessException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ValidateAccessException_Exception(String message, ru.burmistrov.tm.endpoint.ValidateAccessException validateAccessException) {
        super(message);
        this.validateAccessException = validateAccessException;
    }

    public ValidateAccessException_Exception(String message, ru.burmistrov.tm.endpoint.ValidateAccessException validateAccessException, java.lang.Throwable cause) {
        super(message, cause);
        this.validateAccessException = validateAccessException;
    }

    public ru.burmistrov.tm.endpoint.ValidateAccessException getFaultInfo() {
        return this.validateAccessException;
    }
}
